### ISSUE TITLE
Main photo for the slider

### ISSUE THREAD

**Issue by TippyCracker49** [eKraitis/platform#13]

**Comment by TippyCracker49** [comment]
- [ ] Leave only one image (first)
- [ ] Make text look better

**Comment by Bremboo** [comment]
@TippyCracker49 Idk how to fix grey box

**Comment by TippyCracker49** [comment]
I have put a white background, now it's ok :)

**Comment by TippyCracker49** [comment]
@Bremboo maybe let's think of something nicer than right now? :)
