### ISSUE TITLE
Make different header photos for each project

### ISSUE THREAD

**Issue by TippyCracker49** [eKraitis/platform#16]
Choose the best suited image from specific project.

**Comment by Bremboo** [comment]
[Projects Top Images.zip](https://github.com/eKraitis/platform/files/2267362/Projects.Top.Images.zip)

**Comment by TippyCracker49** [comment]
http://luckaconstruction.co.uk/portfolio/project-11/ - this photo doesn't look too good.

**Comment by Bremboo** [comment]
![lucka-construction-bishshopswood-top](https://user-images.githubusercontent.com/42119096/43795675-c06b7702-9a8a-11e8-9a7f-bc43b49cd2d9.jpg)

**Comment by TippyCracker49** [comment]
Let's leave it like that for now.
