### ISSUE TITLE
Prepare info for designers

### ISSUE THREAD

**Issue by TippyCracker49** [eKraitis/platform#19]

**Comment by Bremboo** [comment]
[This is eKraitis.zip](https://github.com/eKraitis/platform/files/2271145/This.is.eKraitis.zip)

You can tweak our colors, or use other vivid ones, feel free to experiment ;) Also, you can put eKraitis name below eKraitis icon if needed. Post image should be 1920x1080px for Facebook, 600x600px for Instagram (we use 72 Pixels/Inch). You can check our banners styline in https://www.facebook.com/ekraitis/?ref=br_rs
