### ISSUE TITLE
Fix slider

### ISSUE THREAD

**Issue by TippyCracker49** [eKraitis/platform#20]
- [x] upload new photos
- [x] make slider smaller (slaideris kiek per masyvus ir užgožia logotipą)

**Comment by Bremboo** [comment]
Can't make any smaller, i think it looks pretty decent.

**Comment by TippyCracker49** [comment]
Need to make it smaller

**Comment by Bremboo** [comment]
Sumazinau margin-top nuo -40 iki -25. Dar galima margin-top:15px; ant iconos maybe

**Comment by TippyCracker49** [comment]
Gal galima bandyti dar labiau ir is sonu galbut normaliai atrodytu
