### ISSUE TITLE
Silko tekstile web design

### ISSUE THREAD

**Issue by TippyCracker49** [eKraitis/platform#34]
Old website: audiniai.com
Some information possibly could be copied from old website.

- [x] Choose a photo for main slider (maybe try to find a better photo)
- [x] Read more isimti mygtuka
- [x] Choose photos for (audiniai, siuvimas)
- [x] Why our shoes pakeisti i Apie mus, sukelti info is senos svetaines, ikelti kelias nuotraukas
- [x] Footer logotipa pakeisti
- [x] Social link i facebook tik
- [x] Apie mus puslapyje graziai padelioti esama teksta, galbut ikelti kelias nuotraukas
- [x] Kontaktu sekcija info sukelti kiek imanoma
- [x] Isversti kontaktu forma, ir kitus string'us
- [x] Change Read more button text to Daugiau, and add link to 'Apie mus' page
- [x] Upload apie mus section photo not as gallery, but as single image. When you press on image it shouln't pop up
- [x] Create pages for Audiniai ir Siuvimas and add some info and photos from old website or your own, also add links to it from homepage
- [x] Add shops info in contacts page 
- [x] Change favicon
- [x] Maybe add some text in main photo something like "Cia prasideda mada!"
- [x] sujungti abi savanoriu parduotuves i viena. Tik poto isskirti 1a ir 2a

**Comment by vtorpeda** [comment]
Dėl social vieną gerą pluginą turiu minty, paklausiu pavadinimo
