### ISSUE TITLE
ISS Fixes

### ISSUE THREAD

**Issue by TippyCracker49** [eKraitis/platform#46]
- [x] Remote support button style (normal orange as everywhere else)
- [x] Working hours should be 24/7 (same in contact section)
- [x] email: help@infosystemsypport.com (same in contact section)
- [x] No location (same in contact section)
- [x] Fix logo
- [x] Create products section (grey logos in one image) for their services
- [x] Fix contact section, make responsive, make font smaller, center
- [x] Change I-VI    24/7 to 24/7 Support
- [x] Add Server Management text
- [x] Delete http://iss.kraitis.lt/contact-us/ page 
- [x] Slider contact us button should go to the bottom
- [x] Upload last service text (slack) 
- [x] Fix this
<img width="1271" alt="screen shot 2018-08-28 at 21 09 15" src="https://user-images.githubusercontent.com/29943484/44741859-0b72e500-ab07-11e8-9790-431b9d1b1add.png">

Backup& Disaster Recovery – Veeam, NetBackup, Storage Craft, Axcient Backup
Network Solutions – Cisco, Juniper, HP ProCurve, Ubiquiti, Ruckus
Server Management – HP, Dell
27/7 Infrastructure Management – ITIL (https://consultantsfactory.com/wp-content/uploads/2018/06/ITIL.jpg)
Security & Compliance – HIPAA Compliance

**Comment by Bremboo** [comment]
Products section nukeliam ryt, dar pora questions bus.
