### ISSUE TITLE
3 Facebook posts

### ISSUE THREAD

**Issue by TippyCracker49** [eKraitis/platform#5]
- [ ] 2 banners with created projects
- [x] one other post

**Comment by Bremboo** [comment]
![ekraitis-post-1](https://user-images.githubusercontent.com/42119096/43795704-ded4d4d6-9a8a-11e8-868e-bd11f7e2ce74.jpg)

**Comment by TippyCracker49** [comment]
Very nice 👍 But we need it in lithuanian :)

**Comment by Bremboo** [comment]
![ekraitis-post-1](https://user-images.githubusercontent.com/42119096/43853250-43b56bb4-9b48-11e8-90d0-be3bd8b372a4.jpg)
![ekraitis-post-2](https://user-images.githubusercontent.com/42119096/43853251-43d27254-9b48-11e8-91c8-f400dc1fc2c3.jpg)

Parasyk tiek dizaineriam, kad padarytu su projektais musu koki viena bent.

**Comment by TippyCracker49** [comment]
First one is already posted. second is like from 90s so need to select different fact :) Also banners need to be different.
