### ISSUE TITLE
Fix photos

### ISSUE THREAD

**Issue by TippyCracker49** [eKraitis/platform#6]
- [x] Pick photos for banners, slider
- [x] Project slider is too big (height)
- [x] Make portfolio 2x3 
- [x] Footer image
- [x] Page header image 
- [x] Upload a better project image (http://luckaconstruction.co.uk/portfolio/project-11/)

**Comment by Bremboo** [comment]
If pool image doesn't satisfy the client, then please send wider images, bcuz everyone one of them is squared AF. Alternative: 

![lucka-construction-bishshopswood-top-2](https://user-images.githubusercontent.com/42119096/44043695-24b381c8-9f2c-11e8-8d9c-dc01afd604d4.jpg)
